name: Daily Check Maps

on:
  schedule:
    - cron:  "0 8 * * *"
  workflow_dispatch:
    branches: [main]

jobs:
  download:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.TOKEN_MAPA }}
      SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
      PASSWORD_EMAIL: ${{ secrets.PASSWORD_EMAIL }}
      RECEIVE_EMAIL: ${{ secrets.RECEIVE_EMAIL }}

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run the script
      run: python setup.py

    - name: Configure o Git
      run: |
        git config user.email "mayara.daher@gmail.com"
        git config user.name "mayaradaher"

    - name: Adicionar arquivo gerado ao Git
      run: |
        git add data/data_previous.xlsx
        git add data/data_today.xlsx

    - name: Checar status
      run: |
        git status

    - name: Fazer commit das alterações
      run: |
        git commit -m "Adicionando arquivo gerado" || echo "Nothing to commit"

    - name: Push para o repositório
      run: |
        git push
